---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: dz2
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    dz2: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: dz2
spec:
  selector:
    matchLabels:
      dz2: ""
  template:
    metadata:
      labels:
        dz2: ""
    spec:
      containers:
      - name: dz2
        image: dubec/home_works:dz1_v01
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: HELLO_MSG
          value: stranger
